Raise RuntimeError when solve_ivp fails
Before this, errors from solve_ivp were not caught. This resulted in
cryptic error messages such as this one:

```
  File "dymos/dymos/transcriptions/solve_ivp/components/segment_simulation_comp.py", line 262, in compute
    outputs['states:{0}'.format(name)] = sol.y[pos:pos+size, :].T
  File "OpenMDAO/openmdao/vectors/vector.py", line 371, in __setitem__
    (name, oldval.shape, value.shape))
ValueError: Incompatible shape for 'states:r': Expected (10, 1) but got (3, 1).
```

With this modyfication, the message is much nicer and is triggered
immediatilly after the error, e.g.

```
  File "dymos/dymos/transcriptions/solve_ivp/components/segment_simulation_comp.py", line 259, in compute
    raise RuntimeError('solve_ipv failed', sol.message)
RuntimeError: ('solve_ipv failed', 'Required step size is less than spacing between numbers.')